### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by andyhe0x21** [ah98607/mvc-most-valuable-coder#1]
Hello everyone,

Welcome to this project! Before we actually start coding, let's follow a few simple steps.

**Grab the Latest Change**
I have created a repo with the skeleton of all most files we need. I assumed that you have all done cloning the repo, then please run
`git pull origin master`
in that directory. If you have not, then simply run
`git clone https://github.com/ah98607/mvc-most-valuable-coder.git`

**Create and Switch to Your Own Branch**
After you have the repository with the skeleton, you will need create your own branch so all of your later work will be done in that branch. To create a branch and switch to it from the default master branch, simply do
`git branch <BRANCH_NAME>`
`git checkout <BRANCH_NAME>`

**Commit, Push, Merge, Pull**
Now you are on your own branch. Next time, when you want the master branch to merge the changes you make in your own development branch, you will need to create a pull request. I will review the code and merge your change. It would be a good idea that we all make some minor changes before Wednesday's class and we will sit together to go through the commit/push/merge/pull process in case some of you might have forgot the details of the process.

**GitHub "Issue" System**
This message was sent through GitHub's "Issue" feature (you may notice it is the second tab under the repo name). We will use it for task assignment, bug tracking and other necessary team communication. One thing that the feature offers is that we can associate commits by a contributor with the "issue" we find earlier. It also sends automatic email notification if any update is available.

**Let's Get Started**
Thank you for reading this post. Let's work closely and make it work! Feel free to raise issue and help each other!

Thanks,
Andy

**Comment by MelindaHasselbring** [comment]
Trevon/Rick, need help on the front end.  Let's talk about it tomorrow.
