### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by andyhe0x21** [ah98607/mvc-most-valuable-coder#3]
Hello Melinda

Can you start designing the main page? For this week, we only need a single page framework, just like the one we discussed yesterday, which has a text area, a submit button, a result displaying area, and a top user list.

You may use my prototype (https://stormy-harbor-77255.herokuapp.com/ (heroku site) and https://github.com/ah98607/TinyCodeJudge (github) as reference (please note that my prototype does not have a top user list yet).

At this time, we have not integrated any real functionality. So the main page will just contain static elements and you don't need to worry about any javascript.

Please make sure you work in your own branch (you can check your current branch by running `git branch`).

**Comment by MelindaHasselbring** [comment]
sorry, Andy, I just got this message.  Yes, that's what i've been doing
this AM.

**Comment by andyhe0x21** [comment]
Don't worry! I believe we have enough time and I will clarify on something like databsae config in tonight class. If you are still not able to get server run on you machine, feel free to comment here and let me know.

**Comment by MelindaHasselbring** [comment]
Issue resolved by pull reqeust #8
