### ISSUE TITLE
implement Autocomplete functionality

### ISSUE THREAD

**Issue by MelindaHasselbring** [ah98607/mvc-most-valuable-coder#38]
As a user, I would like an autocompletion functionality so that i don't have to type all the words in the code field.

**Comment by andyhe0x21** [comment]
This is a cool feature. Do you know if Ace has some kind of support of this?

**Comment by andyhe0x21** [comment]
I would suggest that we don't do it because we have limited time and this is actually not a very important feature. Let's focus on testing the app.

**Comment by MelindaHasselbring** [comment]
yeah, that is fine.

**Comment by MelindaHasselbring** [comment]
closing this issue as "will not implement".
