### ISSUE TITLE
Code field instruction

### ISSUE THREAD

**Issue by MelindaHasselbring** [ah98607/mvc-most-valuable-coder#41]
As a user, I would like a well written instruction so that I know how to use the MCV accordingly.

in the code field, please include the ff:    // Click the start button, then start writing your codes here.

**Comment by MelindaHasselbring** [comment]
Andy, I assigned this to me because you have so much to do.  Although I know yo don't want me to touch the html, you can re-assign it to you Andy if you want.

**Comment by andyhe0x21** [comment]
done #44
