### ISSUE TITLE
Add refresh button 

### ISSUE THREAD

**Issue by MelindaHasselbring** [ah98607/mvc-most-valuable-coder#42]
Refresh for me means start over,  in computing the word refresh means refreshes the app or web page, by displaying its original state.

As a user, I would like to be able to refresh the page by clicking a Refresh button.
Clicking "Refresh" button will re-instate the app's default state as follows:
1.) remove any code entered in the code field
2.) show the" select  a problem" button
3.) display the start button
4.) set the clock back to 0:0
5.) hide the timer

**Comment by MelindaHasselbring** [comment]
either of this buttons would be nice.
http://www.clker.com/cliparts/v/d/5/B/U/P/refresh-button-png-md.png
http://www.free-icons-download.net/images/blue-refresh-button-icon-65919.png

**Comment by andyhe0x21** [comment]
done #44
