### ISSUE TITLE
Font-size in Ace editor

### ISSUE THREAD

**Issue by andyhe0x21** [ah98607/mvc-most-valuable-coder#50]
Can we increase the font-size? We need font-size to be larger so the audience can see it more easily during the presentation.

(I could not find where I can set it. Probably we need to add a JS line to set it?)

**Comment by MelindaHasselbring** [comment]
this is done. increased font size to 20px.
increased editor font size to 20px #51

**Comment by andyhe0x21** [comment]
This change was merged. Please do "git pull origin master" in your branch.

Just FYI
1. this change will not directly go to Heroku because I need to run a Heroku command to sync remote server on Heroku.
2. Changing "Name" -> "Enter your user name" will cause one thing to not work. I will fix it tonight.

I will leave this issue open and will close it once I get both 1 and 2 done tonight.

**Comment by andyhe0x21** [comment]
All done in #59
