### ISSUE TITLE
#username, "Enter username" do not trigger username validation

### ISSUE THREAD

**Issue by MelindaHasselbring** [ah98607/mvc-most-valuable-coder#56]
if (username == "Name"); required validation is not triggered.

**Comment by MelindaHasselbring** [comment]
Fixed:
replaced "Name" with  "Enter username"
if (username == "Enter username");   // coding.js line 128.

**Comment by MelindaHasselbring** [comment]
tested in local branch. Passed. 8/9/17

**Comment by andyhe0x21** [comment]
Fixed. But will be replaced with placeholder-text button.
