### ISSUE TITLE
top3 MVC stars & name need space in between.

### ISSUE THREAD

**Issue by MelindaHasselbring** [ah98607/mvc-most-valuable-coder#73]
see image below 
![top3a](https://user-images.githubusercontent.com/23516873/29187557-0c3e3586-7dc5-11e7-832d-de1c36a63374.JPG)

**Comment by andyhe0x21** [comment]
Fixed.

**Comment by MelindaHasselbring** [comment]
Andy, for “Problem: Reverse A String” the stars and names still need space.  The other problem though is already fixed.

**Comment by andyhe0x21** [comment]
Can you try again?
https://mvc-most-valuable-coder.herokuapp.com/

**Comment by andyhe0x21** [comment]
Fixed
