### ISSUE TITLE
First time winner's name + score does not get displayed synchronously.

### ISSUE THREAD

**Issue by MelindaHasselbring** [ah98607/mvc-most-valuable-coder#78]
First time winner's name + score does not get displayed synchronously.

Expected: 
Should be displayed as soon as the code was validated correct.

Workaround :
User to click refresh button, click Choose Problem, or refresh the browser.

<img width="855" alt="screen shot 2017-08-10 at 6 50 36 pm" src="https://user-images.githubusercontent.com/23516873/29198943-38f395ac-7dfd-11e7-90a6-85a06368b3d0.png">

**Comment by MelindaHasselbring** [comment]
Andy,  i don't think this is a deal breaker.  You may chose to fix it or not.  If you wont. just comment in here and close the issue.

**Comment by andyhe0x21** [comment]
This is actually a bug. I have the code to update the rank when displaying the congratulation message but it somehow does not work.

Currently I am adding "Please refresh to update rank" as a walk-around.

Will investigate the reason behind it.

**Comment by MelindaHasselbring** [comment]
Add'l note:
This is only happening on First time winners, where their name aren't in the database yet.  The second time they get the correct answer and they ranked high enough to be on the top3, the rank list is updated right away.

**Comment by andyhe0x21** [comment]
Can you try again?
https://mvc-most-valuable-coder.herokuapp.com/

**Comment by andyhe0x21** [comment]
Fixed.

Actually I did not do anything but it just worked. I don't know why.
